<template>
  <header>
    <VToolbar>
      <VToolbarTitle>Welcome!</VToolbarTitle>
      <VSpacer />
      <VBtn
        flat
        to="/"
      >
        Home
      </VBtn>
      <VBtn
        flat
        to="/about"
      >
        About
      </VBtn>
    </VToolbar>
  </header>
</template>
